var movies = [
  "Rocky Horror Picture Show",
  "Grease",
  "Pirates of the Caribbean",
  "Boondock Saints",
  "Fight Club",
  "Starsky and Hutch",
  "Neverending Story",
  "Blazing Saddle",
  "Airplane",
  "The Princess Bride",
  "Anchorman",
  "Napoleon Dynamite",
  "Labyrinth",
  "Saw",
  "Saw II",
  "White Noise",
  "White Oleander",
  "Anger Management",
  "50 First Dates",
  "The Princess Diaries",
  "The Princess Diaries 2",
  "Scream",
  "Scream 2",
  "Scream 3",
  "Scary Movie",
  "Scary Movie 2",
  "Scary Movie 3",
  "Scary Movie 4",
  "American Pie",
  "American Pie 2",
  "American Wedding",
  "Harry Potter and the Sorcerer’s Stone",
  "Harry Potter and the Chamber of Secrets",
  "Harry Potter and the Prizoner of Azkaban",
  "Harry Potter and the Goblet of Fire",
  "Harry Potter and the Order of the Phoenix",
  "Harry Potter and the Half-Blood Prince",
  "Harry Potter and the Deathly Hallows Part 1",
  "Harry Potter and the Deathly Hallows Part 2",
  "Resident Evil",
  "Resident Evil 2",
  "The Wedding Singer",
  "Little Black Book",
  "Lilo & Stitch",
  "Finding Nemo",
  "Finding Neverland",
  "Signs",
  "The Grinch",
  "Texas Chainsaw Massacre The Beginning",
  "White Chicks",
  "Butterfly Effect",
  "13 Going on 30",
  "iRobot",
  "Robots",
  "Dodgeball: A True Underdog Story",
  "Universal Soldier",
  "Lemony Snicket: A Series Of Unfortunate Events",
  "Along Came Polly",
  "Deep Impact!",
  "Kingpin",
  "Never Been Kissed",
  "Meet The Parents",
  "Meet the Fockers",
  "Eight Crazy Nights",
  "Joe Dirt",
  "KING KONG",
  "A Cinderella Story",
  "The Terminal",
  "The Lizzie McGuire Movie",
  "Passport to Paris",
  "Dumb & Dumber",
  "Dumber & Dumberer",
  "Final Destination 1",
  "Final Destination 2",
  "Final Destination 3",
  "Halloween 1",
  "The Ring",
  "The Ring 2",
  "Surviving X-MAS",
  "Flubber",
  "Harold & Kumar Go To White Castle",
  "Practical Magic",
  "Chicago",
  "Ghost Ship",
  "From Hell",
  "Hellboy",
  "Secret Window",
  "I Am Sam",
  "The Whole Nine Yards",
  "The Whole Ten Yards",
  "The Day After Tomorrow",
  "Child's Play",
  "Seed of Chuck",
  "Bride of Chucky",
  "Ten Things I Hate About You",
  "Just Married",
  "Gothika",
  "Nightmare on Elm Street",
  "Sixteen Candles",
  "Remember the Titan",
  "Coach Carter",
  "The Grudge",
  "The Mask",
  "Son Of The Mask",
  "Bad Boys",
  "Bad Boys 2",
  "Joy Ride",
  "Lucky Number Slevin",
  "Ocean's Eleven",
  "Ocean's Twelve",
  "Bourne Identity",
  "Bourne Supremacy",
  "Bourne Legacy",
  "Bourne Ultimatum",
  "Jason Bourne",
  "Lone Star",
  "Bedazzled",
  "Predator I",
  "Predator II",
  "The Fog",
  "Ice Age",
  "Ice Age 2: The Meltdown",
  "Curious George",
  "Independence Day",
  "Cujo",
  "A Bronx Tale",
  "Darkness Falls",
  "Christine",
  "ET",
  "Children of the Corn",
  "My Bosses Daughter",
  "Maid in Manhattan",
  "War of the Worlds",
  "Rush Hour",
  "Rush Hour 2",
  "Rush Hour 3",
  "The Best Bet",
  "How to Lose a Guy in 10 Days",
  "She's All That",
  "Calendar Girls",
  "Sideways",
  "Mars Attacks",
  "Event Horizon",
  "Ever After",
  "Wizard of Oz",
  "Forrest Gump",
  "Big Trouble in Little China",
  "The Terminator",
  "The Terminator 2",
  "The Terminator 3",
  "X-Men",
  "X-2",
  "X-3",
  "Spider-Man",
  "Spider-Man 2",
  "Sky High",
  "Jeepers Crepers",
  "Jeepers Creepers 2",
  "Catch Me If You Can",
  "The Little Mermaid",
  "Freaky Friday",
  "Reign of Fire",
  "The Skulls",
  "Cruel Intentions",
  "The Hot Chick",
  "Shrek️",
  "Shrek 2",
  "Swimfan",
  "Miracle on 34th Street",
  "Old School",
  "The Notebook",
  "K-Pax",
  "Krippendorf's Tribe",
  "A Walk to Remember",
  "Ice Castles",
  "Boogeyman",
  "The 40-year-old Virgin",
  "Lord of the Rings. Fellowship of the Ring",
  "Lord of the Rings The Two Towers",
  "Lord of the Rings Return Of the King",
  "Indiana Jones and the Raiders of the Ark",
  "Indiana Jones and the Temple of Doom",
  "Indiana Jones and the Last Crusade",
  "Basketball Diaries",
  "Hostel",
  "Waiting for Guffman",
  "  House of 1000 Corpses",
  "Devils Reject",
  "Elf",
  "Highlander",
  "Mothman Prophecies️",
  "American History X",
  "The Jacket",
  "Kung Fu Hustle",
  "Shaolin Soccer",
  "Night Watch",
  "Monsters Inc",
  "Titanic",
  "Monty Python and the Holy Grail",
  "Shaun Of the Dead",
  "Willard",
  "High Tension",
  "Club Dread",
  "Hulk",
  "Dawn Of the Dead",
  "Hook",
  "Chronicles Of Narnia: The Lion the Witch and the Wardrobe",
  "28 days later",
  "Orgazmo",
  "Phantasm",
  "Water World",
  "Kill Bill Vol 1",
  "Kill Bill Vol 2",
  "Mortal Kombat",
  "Wolf Creek",
  "Kingdom of Heaven",
  "The Hills Have Eyes",
  "I Spit on Your Grave",
  "The Last House on the Left",
  "Re-Animator",
  "Army of Darkness",
  "Star Wars Ep. I The Phantom Menace",
  "Star Wars Ep. II Attack of the Clones",
  "Star Wars Ep. III Revenge of the Sith",
  "Star Wars Ep. IV A New Hope",
  "Star Wars Ep. V The Empire Strikes Back",
  "Star Wars Ep. VI Return of the Jedi",
  "Ewoks Caravan Of Courage",
  "Ewoks The Battle For Endor",
  "The Matrix",
  "The Matrix Reloaded",
  "The Matrix Revolution",
  "Evil Dead1",
  "Evil Dead 2",
  "Team America: World Police",
  "Red Dragon",
  "Silence of the Lambs",
  "Hannibal",
  "The Breakfast Club",
  "Fast Times at Ridgemont High",
  "Ferris Bueller's Day Off",
  "Grown Ups",
  "Dazed and confused",
  "Ridiculous 6",
  "Pretty in Pink",
  "The Tooth Fairy",
  "Polar Express",
  "X-Men: Apocalypse",
  "Fantastic Four",
  "Leprechaun",
  "Mad Money",
];
